version: '3.8'
services:
  nest-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=nestjs_db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjs_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
